version: '3.8'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      args:
        - target=development
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    environment:
      RR_ENV: development
      RR_PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: my-secret-pw
      DB_NAME: reading_record
      DB_MAX_OPEN_CONNS: 10
      DB_MAX_IDLE_CONNS: 10
      DB_MAX_IDLE_TIME: 15m
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_SENDER: $SMTP_SENDER
  db:
    image: mysql:8.0.31
    restart: always
    ports:
      - '33306:3306'
    volumes:
      - reading_record_db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: reading_record
  migrate:
    build: ./migrations
    depends_on:
      - db
    command: ['up']
    volumes:
      - ./migrations/migrations:/migrations
    environment:
      WAIT_HOSTS: db:3306
      MIGRATIONS_DIR: /migrations
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: my-secret-pw
      DB_NAME: reading_record
volumes:
  reading_record_db_data:
