CREATE TABLE IF NOT EXISTS tokens (
  hash BINARY(32) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
  expiry DATETIME NOT NULL,
  scope VARCHAR(60) NOT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;