CREATE TABLE IF NOT EXISTS daily_progresses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  read_date DATE NOT NULL,
  read_page int NOT NULL,
  reading_id BIGINT NOT NULL REFERENCES readings ON DELETE CASCADE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  version BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;