name: Build and publish Docker image

on:
  push:
    branches:
      - test_ci_migrate

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get dependecies
        run: go mod tidy

      - name: Build
        run: go build -v cmd/api

  migrate:
    name: DB migration
    runs-on: ubuntu-latest
    environment: database
    steps:
      - name: Install golang-migrate
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
          echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
          sudo apt update
          sudo apt install -y migrate

      - name: Migrate production database
        run: migrate -path migrations/migrations -database ${{ secrets.DATABASE_URL }} up

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          target: deploy
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
